[versions]
spotbugs = "4.8.3"
shadow = "9.0.0"
junit = "5.10.2"
bstats = "3.1.0"
velocity-api = "3.1.1"
jackson = "2.16.1"
semver = "1.3.0"
hangar = "0.1.3"
bungeecord-api = "1.20-R0.2"

[libraries]
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
bstats-bungeecord = { module = "org.bstats:bstats-bungeecord", version.ref = "bstats" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-velocity = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
semver = { module = "net.swiftzer.semver:semver", version.ref = "semver" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref = "bungeecord-api" }


[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
